version: '3.8'

services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    image: ollama/ollama:0.1.27-rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    devices:
      - /dev/dri
      - /dev/kfd
    group_add:
      - video
    tty: true
    environment:
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      - HCC_AMDGPU_TARGETS=gfx900
#      - OLLAMA_ORIGINS="app://obsidian.md*"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
